include: package:flutter_lints/flutter.yaml
analyser:
  errors:
    prefer_interpolation_to_compose_strings: ignore
analyzer:
  errors:
    prefer_interpolation_to_compose_strings: ignore
    depend_on_referenced_packages: ignore
