name: fourier_forge
description: "Irfan Syakir's FYP"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.3
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.12

flutter:
  uses-material-design: true
  assets:
  - lib/assets/animations/
  - lib/assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_logo.png"

flutter_native_splash:
  color: "#7986CB"  
  image: splash_screen.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true

