name: fourier_forge
description: "Irfan Syakir's FYP"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.3
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/animations/
